### ISSUE TITLE
Community: replace thumbnail classes with inline styles

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-cloud#310]
Some community thumbnails are using classes for styling, the names of which are clashing depending on what order they are displayed.

We need to remove these classes and use inline styles, preferably the `fill`, `stroke` attributes.

**Comment by rossbulat** [comment]
@TingALin did you make any progress with this?

**Comment by rvalle** [comment]
@TingALin , @rossbulat 

isn't this addressed in https://github.com/paritytech/polkadot-cloud/pull/318/commits/a2506b3e14780cfc0bd55efb77cc184461d2f383

However, it has not been published to NPM repo yet.

I am trying to adopt this UI resources for Polkawatch going forward.

I also have positioning problem with fearless thumnail which seems to have a significant offset.

**Comment by rossbulat** [comment]
Hi @rvalle,

The `light` and `dark` are the only classes that I plan to keep in there, as they allow some simple theming on the SVGs. I think this was a miscommunication with the work @TingALin did.

That said, these classes are not set in stone, if they do not meet your requirements we can definitely revise.

I will jump onto this shortly and resolve the other classes.

**Comment by rossbulat** [comment]
It appears this has been resolved in the staking dashboard already, will update the package shortly.

**Comment by rossbulat** [comment]
Latest updates now published to 0.1.5.

**Comment by rvalle** [comment]
@rossbulat many thanks for the quick response!

I am not an expert in packing TS modules, but I am not sure it is published as you intend.

types.ts is missing, and my IDE can only find components under  `@polkadotcloud/community/lib/extensions`. I am not sure if this is what you intended or if something went wrong.

types missing definitely breaks the supplied code.

also I tried both 0.1.5 and 0.1.7

**Comment by rossbulat** [comment]
Hey @rvalle, my apologies, there was an error with the build config that caused errors in the build. I have just pushed version `0.1.10` - please let me know if you continue to experience issues.

**Comment by rvalle** [comment]
@rossbulat, no worries, I am happy to test. I think it is a good idea to have common UI resources for many DAPPs so there is a consistent community look.

Let me test it out...

**Comment by rvalle** [comment]
![looking better](https://github.com/paritytech/polkadot-cloud/assets/412837/3e17bbaf-4360-4082-9ce2-414ab522a960)

Now looking much better at first try and no added styling.

I can see staking dashboard looks nicer, I think is because the stroke in use, will look into it.

Also Subwallet goes slightly outside its box, but don't really understand why yet.

**Comment by rossbulat** [comment]
Awesome! 

The Subwallet icon is not perfectly square, so to get all the icons the correct height we can just add a bit of css. The  svg container can also dictate `currentColor`, which talisman and subwallet support, so they can change with light and dark theming. Here is what staking dashboard uses:

```
.icon {
    color: var(--text-color-primary); 
    width: 100%;

    svg {
      max-width: 2.6rem;
      max-height: 2.6rem;
    }
  }
```

**Comment by rvalle** [comment]
Yes, I ended with this:

```
                                    <Box display={'flex'}
                                         justifyContent={'center'}
                                        sx={{
                                            mr: 2,
                                            color: 'var(--text-color-primary)',
                                            width: iconSize,
                                            height: iconSize,
                                            '& svg': {
                                                maxHeight: iconSize,
                                                maxWidth: iconSize
                                            }
                                        }}
                                    >
                                        <Icon/>
                                    </Box>
```

to get it with within the box and also centered. thanks!
