### ISSUE TITLE
Utils: `ellipsisFn` to support placement (`START`, `CENTER`, `END`)

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-cloud#574]
Polkawatch have began integrating decentralisation info into the staking dashboard here: https://github.com/paritytech/polkadot-staking-dashboard/pull/1379

One of the formatting features is ellipsizing the graph labels using the `ellipsize` package. If we can expand `ellipsisFn` from utils to support ellipsis position, we will not need to add this dependency.

**Comment by wirednkod** [comment]
Ellipsisfn already supports placement: https://github.com/paritytech/polkadot-cloud/blob/main/packages/utils/lib/index.ts#L466-L470

**Comment by rossbulat** [comment]
Thanks @wirednkod! Apologies for not noticing that, staking dashboard should really have more variation and utilise `position`!
