### ISSUE TITLE
Breaking change: rename validator operator "thumbnails" to "icons"

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-cloud#628]
Bringing some consistency to our assets catalogue.

**Comment by wirednkod** [comment]
We need to revisit this - as a category addition I would like to have is the "polkadot-icons" - even though they already exist inside a w3f repository. I think Polkadot Cloud can be a consistent service for everything around polkadot

**Comment by rossbulat** [comment]
Closing for now as non-urgent
