### ISSUE TITLE
Module not found when using `ExtensionsProvider` component

### ISSUE THREAD

**Issue by paulormart** [paritytech/polkadot-cloud#734]
Hi Guys, 

Thanks for putting this together, I was exploring this library so I can use it in some of my tools to better handle the Web3 extensions, but compilation is currently failing with the error below, am I missing something?

```
Failed to compile.

Module not found: Error: Can't resolve '@polkadot-cloud/assets/extensions' in '.../my-app/node_modules/@polkadot-cloud/react/connect/ExtensionsProvider'
ERROR in ./node_modules/@polkadot-cloud/react/connect/ExtensionsProvider/index.js 13:0-68
Module not found: Error: Can't resolve '@polkadot-cloud/assets/extensions' in '.../my-app/node_modules/@polkadot-cloud/react/connect/ExtensionsProvider'

webpack compiled with 1 error
```

I've just set up a new project [here](https://github.com/turboflakes/my-app) with `npx create-react-app my-app` and installed all `polkadot-cloud` dependencies to open this issue.

Many thanks

**Comment by rossbulat** [comment]
Hey @paulormart, thanks for raising! 

I believe this may be because the `assets` package is compiled into Typescript and not vanilla Javascript. This was indeed an oversight, and will expedite a fix.

**Comment by rossbulat** [comment]
@paulormart should be good to go, please let me know if there are further issues.

**Comment by paulormart** [comment]
Working well @rossbulat Thanks.

**Comment by paulormart** [comment]
Sorry it might be a different issue, but just reopening in case is related.

Going through the [examples](https://polkadot.cloud/extension-accounts-provider). In the component below i was expecting `extensions` to automatically detect and contain the objects for each extension i have installed in the browser (chrome Version 117.0.5938.92 (Official Build) (arm64)), however all i get is an empty array. Also `extensionsStatus={}` and `checkingInjectedWeb3=true`

[example src](https://github.com/turboflakes/my-app/blob/main/src/ConnectAccounts.js)
```
import {
    useExtensions,
    useExtensionAccounts,
  } from '@polkadot-cloud/react/hooks';

export default function ConnectAccounts() {
  const { extensions, extensionsStatus, checkingInjectedWeb3 } = useExtensions();
  const { connectExtensionAccounts } = useExtensionAccounts();
  
  console.log("extensions", extensions, extensionsStatus, checkingInjectedWeb3);
  const extension = extensions.find((e) => e.id === 'subwallet-js');

  return (
    <>
      <button
        type="button"
        onClick={() => {
          if (extension) connectExtensionAccounts(extension);
        }}
      >
        Connect to Subwallet JS
      </button>
    </>
  );
};
```

**Comment by rossbulat** [comment]
@paulormar Have you wrapped your JSX with `<ExtensionsProvider>`, with `ConnectAccounts` embedded within it? It looks like the hook is just returning the default values, which it will do if the provider is not found.

**Comment by wirednkod** [comment]
@paulormart you need to:

```ts
import { ExtensionsProvider } from "@polkadot-cloud/react/providers";
....
ReactDOM.createRoot(document.getElementById("root")!).render(
  <ExtensionsProvider> {*/  This should be with rest of Providers the first tags in renders /*}
        <App />
  </ExtensionsProvider>
);
```

and then:
```ts
import { useExtensions } from "@polkadot-cloud/react/hooks";

function App() {
  const [count, setCount] = useState(0);
  const { extensions } = useExtensions();
  console.log("extensions", extensions);
  }
```

Already tested that in a sample app and I get:

![image](https://github.com/paritytech/polkadot-cloud/assets/5408605/af4c96e7-904a-4536-95a1-76cfbdb736cd)

**Comment by paulormart** [comment]
@wirednkod @rossbulat Many Thanks for the feedback.

Just tried it, so removing the `React.StrictMode` wrapper from my tiny example works well, just not sure why that is the case, for example:

No issues, if initiated like:
```
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<AppWithProviders />);
```

And no issues if `React.Fragment` is used:

```
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.Fragment>
    <AppWithProviders />
  </React.Fragment>
);
```

But with `React.StrictMode` which is the default that is used when someone creates a new app via  `npx create-react-app my-app` doesn't work (the extensions are not loaded) which lead me to believe there was still some issue here.

```
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <AppWithProviders />
  </React.StrictMode>
);
```

**Comment by wirednkod** [comment]
Thank you for that @paulormart .
I have replicated the scenario and indeed StrictMode does not allow the providers to work.
Though if StrictMode.is placed AFTER the providers everything works as expected.

I am not 1000% sure how exactly StrictMode works under the hood but i intend to find out. 

I propose until any update to place it after the ExtensionProviders for now

**Comment by paulormart** [comment]
All good from my side, just realised that the repo i created for this issue was a private repo :/ sorry for that it didn't really help in the end.

Closing this issue, thanks again.
